openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: Authentication API documentation
  contact:
    email: loinguyenlamthanh@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
tags:
  - name: Index
    description: Index related endpoints
  - name: Migrate
    description: Migrate related endpoints
  - name: AuditLog
    description: AuditLog related endpoints
  - name: Auth
    description: Auth related endpoints
  - name: Franchise
    description: Franchise related endpoints
  - name: Role
    description: Role related endpoints
  - name: User
    description: User related endpoints
  - name: UserFranchiseRole
    description: UserFranchiseRole related endpoints
  - name: CartItem
    description: CartItem related endpoints
  - name: Cart
    description: Cart related endpoints
  - name: Category Franchise
    description: Franchise menu category endpoints
  - name: Category
    description: Category related endpoints
  - name: Client
    description: Client related endpoints
  - name: Customer Auth
    description: Customer authentication related endpoints
  - name: CustomerFranchise
    description: CustomerFranchise related endpoints
  - name: Customer
    description: Customer related endpoints
  - name: Dashboard
    description: Dashboard related endpoints
  - name: Delivery
    description: Delivery related endpoints
  - name: Inventory
    description: Inventory related endpoints
  - name: LoyaltyRule
    description: LoyaltyRule related endpoints
  - name: LoyaltyTransaction
    description: LoyaltyTransaction related endpoints
  - name: OrderItem
    description: OrderItem related endpoints
  - name: OrderStatusLog
    description: OrderStatusLog related endpoints
  - name: Order
    description: Order related endpoints
  - name: Payment
    description: Payment related endpoints
  - name: Product Category Franchise
    description: Product Category Franchise related endpoints
  - name: Product Franchise
    description: Product Franchise related endpoints
  - name: Product
    description: Product related endpoints
  - name: Promotion
    description: Promotion related endpoints
  - name: Refund
    description: Delivery related endpoints
  - name: ShiftAssignment
    description: Shift assignment related endpoints
  - name: Shift
    description: Shift related endpoints
  - name: Voucher
    description: Voucher related endpoints
paths:
  /:
    get:
      summary: Index API - check server status
      tags:
        - Index
      responses:
        '200':
          description: Server is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: API is running
