export const COLLECTION_NAME = {
  AUDIT_LOG: "AuditLog",
  FRANCHISE: "Franchise",
  USER: "User",
  ROLE: "Role",
  USER_FRANCHISE_ROLE: "UserFranchiseRole",
  CATEGORY: "Category",
  PRODUCT: "Product",
  INVENTORY: "Inventory",
  INVENTORY_LOG: "InventoryLog",
  CUSTOMER: "Customer",
  CUSTOMER_FRANCHISE: "CustomerFranchise",
  CART: "Cart",
  CART_ITEM: "CartItem",
  CART_ITEM_OPTION: "CartItemOption",
  ORDER: "Order",
  ORDER_ITEM: "OrderItem",
  VOUCHER: "Voucher",
  PROMOTION: "Promotion",

  // Master Data
  CATEGORY_FRANCHISE: "CategoryFranchise",
  PRODUCT_FRANCHISE: "ProductFranchise",
  PRODUCT_CATEGORY_FRANCHISE: "ProductCategoryFranchise",
  SHIFT: "Shift",
  SHIFT_ASSIGNMENT: "ShiftAssignment",
};
